[WIP] New resource aws_db_proxy_default_target_group
terraform-providers/terraform-provider-aws pull request #12743
Opened 2020-04-09 08:19 UTC by gazoakley

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates #12690

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
**New Resource:** `aws_db_proxy_default_target_group` (#12743)
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSDbProxyDefaultTargetGroup_'

...
```

2020-08-18 21:03 UTC, teamterraform commented
## Notification of Recent and Upcoming Changes to Contributions

Thank you for this contribution! There have been a few recent development changes that affect this pull request. We apologize for the inconvenience, especially if there have been long review delays up until now. Please note that this is automated message from an unmonitored account. See the [FAQ](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/FAQ.md) for additional information on the maintainer team and review prioritization.

If you are unable to complete these updates, please leave a comment for the community and maintainers so someone can potentially continue the work. The maintainers will encourage other contributors to use the existing contribution as the base for additional changes as appropriate. Otherwise, contributions that do not receive updated code or comments from the original contributor may be closed in the future so the maintainers can focus on active items.

For the most up to date information about Terraform AWS Provider development, see the [Contributing Guide](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/CONTRIBUTING.md). Additional technical debt changes can be tracked with the [`technical-debt` label on issues](https://github.com/terraform-providers/terraform-provider-aws/issues?q=is%3Aopen+is%3Aissue+label%3Atechnical-debt).

As part of updating a pull request with these changes, the most current unit testing and linting will run. These may report issues that were not previously reported.

### Terraform 0.12 Syntax

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/8950
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14417

Version 3 and later of the Terraform AWS Provider, which all existing contributions would potentially be added, only supports Terraform 0.12 and later. Certain syntax elements of Terraform 0.11 and earlier show deprecation warnings during runs with Terraform 0.12. Documentation and test configurations, such as those including deprecated string interpolations (`some_attribute = "${aws_service_thing.example.id}"`) should be updated to the newer syntax (`some_attribute = aws_service_thing.example.id`). Contribution testing will automatically fail on older syntax in the near future. Please see the referenced issues for additional information.

### Action Required: Terraform Plugin SDK Version 2

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14551

The Terraform AWS Provider has been upgraded to the latest version of the Terraform Plugin SDK. Generally, most changes to contributions should only involve updating Go import paths in source code files. Please see the referenced issue for additional information.

### Action Required: Removal of website/aws.erb File

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14712

Any changes to the `website/aws.erb` file are no longer necessary and should be removed from this contribution to prevent merge issues in the near future when the file is removed from the repository. Please see the referenced issue for additional information.

### Upcoming Change of Git Branch Naming

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14292

Development environments will need their upstream Git branch updated from `master` to `main` in the near future. Please see the referenced issue for additional information and scheduling.

### Upcoming Change of GitHub Organization

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14715

This repository will be migrating from https://github.com/terraform-providers/terraform-provider-aws to https://github.com/hashicorp/terraform-provider-aws. No practitioner or developer action is anticipated and most GitHub functionality will automatically redirect to the new location. Go import paths including `terraform-providers` can remain for now. Please see the referenced issue for additional information and scheduling.

2020-09-01 16:29 UTC, bflad commented
@gazoakley just merged in `aws_db_proxy` if you would like to rebase this pull request 🎉  then I can go through this. I think I'm agreeing with this initial implementation of a separate "default" target group resource since its semantics will be different than ones that can potentially be fully managed in the future. 👍

2020-09-01 21:37 UTC, gazoakley commented
@bflad Rebased 👍 . I think I remember seeing in the documentation references to associate target groups with proxies, but there's no actual API operation to do so. I guess AWS intended to provide that function but removed it late on/didn't complete it as the only actual way to create a target group is to create a proxy (which in turn creates the default). Given there are API calls to `DescribeDBProxyTargetGroups`/`ModifyDBProxyTargetGroup` having a separate resource seems like the "Terraform way" of doing things hence why I've gone this route.

2020-09-04 21:14 UTC, bflad requested changes
Hi again @gazoakley 👋  Here's the initial round of feedback. Thank you for splitting up the acceptance testing early! Please reach out if you have any questions or do not have time to implement the items. 👍

2020-09-04 21:14 UTC, bflad commented on aws/resource_aws_db_proxy_default_target_group_test.go
> +}
The "basic" configuration should not include anything optional, e.g. no `connection_pool_config` configuration at all and would be expected to show no differences. 👍

2020-09-04 21:14 UTC, bflad commented on aws/resource_aws_db_proxy_default_target_group_test.go
> +				DBProxyName: aws.String(rs.Primary.ID),
```suggestion
				DBProxyName:     aws.String(rs.Primary.ID),
				TargetGroupName: aws.String("default"),
```

2020-09-04 21:14 UTC, bflad commented on aws/resource_aws_db_proxy_default_target_group_test.go
> +			DBProxyName: aws.String(rs.Primary.ID),
```suggestion
			DBProxyName:     aws.String(rs.Primary.ID),
			TargetGroupName: aws.String("default"),
```

2020-09-10 17:30 UTC, bflad approved these changes
Looks good, thank you @gazoakley 🚀 

Output from acceptance testing:

```
--- PASS: TestAccAWSDBProxyDefaultTargetGroup_Basic (737.81s)
--- PASS: TestAccAWSDBProxyDefaultTargetGroup_MaxIdleConnectionsPercent (740.15s)
--- PASS: TestAccAWSDBProxyDefaultTargetGroup_MaxConnectionsPercent (748.09s)
--- PASS: TestAccAWSDBProxyDefaultTargetGroup_SessionPinningFilters (756.04s)
--- PASS: TestAccAWSDBProxyDefaultTargetGroup_InitQuery (765.73s)
--- PASS: TestAccAWSDBProxyDefaultTargetGroup_ConnectionBorrowTimeout (780.68s)
--- PASS: TestAccAWSDBProxyDefaultTargetGroup_disappears (786.01s)
```

2020-09-10 17:31 UTC, merged