Feature: Root access to Sagemaker notebook instance
terraform-providers/terraform-provider-aws pull request #14184
Opened 2020-07-15 15:09 UTC by dinakar29

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #NA

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
Ability to configure root access for Sagemaker notebook instances
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSSagemakerNotebookInstance_root_access'

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSSagemakerNotebookInstance_root_access -timeout 120m
=== RUN   TestAccAWSSagemakerNotebookInstance_root_access
=== PAUSE TestAccAWSSagemakerNotebookInstance_root_access
=== CONT  TestAccAWSSagemakerNotebookInstance_root_access
--- PASS: TestAccAWSSagemakerNotebookInstance_root_access (652.27s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	653.837s
```

2020-08-23 19:29 UTC, DrFaust92 requested changes
Hey, small change request.

2020-08-23 19:29 UTC, DrFaust92 commented on aws/resource_aws_sagemaker_notebook_instance.go
> +					sagemaker.RootAccessDisabled,
nit, can you change this to `sagemaker.RootAccess_Values()`

2020-08-23 19:29 UTC, DrFaust92 commented on aws/resource_aws_sagemaker_notebook_instance_test.go
> +	role_arn = "${aws_iam_role.foo.arn}"
use tf12 syntax

2020-08-23 19:29 UTC, DrFaust92 commented on aws/resource_aws_sagemaker_notebook_instance_test.go
> +	assume_role_policy = "${data.aws_iam_policy_document.assume_role.json}"
same as above

2020-08-25 12:30 UTC, DrFaust92 approved these changes
LGTM

```
--- PASS: TestAccAWSSagemakerNotebookInstance_root_access (699.92s)
```

2020-08-31 00:25 UTC, dinakar29 commented
@DrFaust92 - Is this good to merge? We are eagerly anticipating this being available in a near future release.

2020-09-23 21:34 UTC, ewbankkit approved these changes
LGTM.

```console
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSSagemakerNotebookInstance_root_access\|TestAccAWSSagemakerNotebookInstance_basic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSSagemakerNotebookInstance_root_access\|TestAccAWSSagemakerNotebookInstance_basic -timeout 120m
=== RUN   TestAccAWSSagemakerNotebookInstance_basic
=== PAUSE TestAccAWSSagemakerNotebookInstance_basic
=== RUN   TestAccAWSSagemakerNotebookInstance_root_access
=== PAUSE TestAccAWSSagemakerNotebookInstance_root_access
=== CONT  TestAccAWSSagemakerNotebookInstance_basic
=== CONT  TestAccAWSSagemakerNotebookInstance_root_access
--- PASS: TestAccAWSSagemakerNotebookInstance_basic (305.93s)
--- PASS: TestAccAWSSagemakerNotebookInstance_root_access (625.81s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	625.849s
```

2020-09-24 22:48 UTC, breathingdust commented
LGTM! 🚀  Thanks @dinakar29 

Verified Acceptance Tests in Commercial (us-west-2)

```console
make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSSagemakerNotebookInstance_root_access\|TestAccAWSSagemakerNotebookInstance_basic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSSagemakerNotebookInstance_root_access\|TestAccAWSSagemakerNotebookInstance_basic -timeout 120m
=== RUN   TestAccAWSSagemakerNotebookInstance_basic
=== PAUSE TestAccAWSSagemakerNotebookInstance_basic
=== RUN   TestAccAWSSagemakerNotebookInstance_root_access
=== PAUSE TestAccAWSSagemakerNotebookInstance_root_access
=== CONT  TestAccAWSSagemakerNotebookInstance_basic
=== CONT  TestAccAWSSagemakerNotebookInstance_root_access
--- PASS: TestAccAWSSagemakerNotebookInstance_basic (332.52s)
--- PASS: TestAccAWSSagemakerNotebookInstance_root_access (671.71s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	673.305s
```

Verified Acceptance Tests in GovCloud (us-gov-west-1)

```console
make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSSagemakerNotebookInstance_root_access\|TestAccAWSSagemakerNotebookInstance_basic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSSagemakerNotebookInstance_root_access\|TestAccAWSSagemakerNotebookInstance_basic -timeout 120m
=== RUN   TestAccAWSSagemakerNotebookInstance_basic
=== PAUSE TestAccAWSSagemakerNotebookInstance_basic
=== RUN   TestAccAWSSagemakerNotebookInstance_root_access
=== PAUSE TestAccAWSSagemakerNotebookInstance_root_access
=== CONT  TestAccAWSSagemakerNotebookInstance_basic
=== CONT  TestAccAWSSagemakerNotebookInstance_root_access
--- PASS: TestAccAWSSagemakerNotebookInstance_basic (297.88s)
--- PASS: TestAccAWSSagemakerNotebookInstance_root_access (693.07s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	694.530s
```

2020-09-24 22:48 UTC, merged