Document breaking change in data source aws_launch_template
terraform-providers/terraform-provider-aws pull request #15135
Opened 2020-09-13 06:38 UTC by arielpeltz

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #15094 

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
Document data source aws_launch_template breaking change in upgrade to 3.0
```

2020-09-17 16:04 UTC, anGie44 commented on website/docs/guides/version-3-upgrade.html.md
> +- [Data Source: aws_launch_template](#data-source-aws_launch_template)
Hi @arielpeltz 👋 Do you mind moving this line below `aws_lambda` to maintain the list in alphabetical order?

2020-09-17 16:05 UTC, anGie44 commented on website/docs/guides/version-3-upgrade.html.md
> +## Data Source: aws_launch_template
Nit: similar comment as above to move this section

2020-09-17 16:07 UTC, anGie44 requested changes
Thank you for this documentation update @arielpeltz! Just a minor comment regarding the physical ordering of the the items, otherwise looks great!

2020-09-18 16:20 UTC, anGie44 approved these changes
Thanks @arielpeltz, LGTM 👍

2020-09-18 16:21 UTC, merged

2020-09-18 16:23 UTC, arielpeltz commented
That was quick @anGie44 .  I was waiting for the tests to finish before requesting a review...  Thanks!!