tests/provider: Fix hardcoded ARN (CloudTrail)
terraform-providers/terraform-provider-aws pull request #15663
Opened 2020-10-15 17:08 UTC by YakDriver

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates #15662

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
NONE
```

The output from acceptance testing (GovCloud):

```
kommer snart
```

The output from acceptance testing (commercial):

```
kommer snart
```

2020-10-16 13:21 UTC, bflad commented
Extraneous go.mod/go.sum changes should be removed 👍

2020-10-16 23:54 UTC, bflad requested changes
Merge conflict 😉

2020-10-17 14:10 UTC, YakDriver commented
What in the world has go done? Fixed.

2020-10-21 18:52 UTC, anGie44 approved these changes
LGTM 🚀

2020-10-21 18:52 UTC, anGie44 commented on aws/resource_aws_cloudtrail_test.go
> +`, cloudTrailRandInt)
🙌 🙌

2020-10-21 19:34 UTC, merged

2020-10-21 19:34 UTC, YakDriver commented on aws/resource_aws_cloudtrail_test.go
> +`, cloudTrailRandInt)
💯