Create separate documentation category for EventBridge
terraform-providers/terraform-provider-aws pull request #15918
Opened 2020-10-29 18:55 UTC by gdavison

CloudWatch Events has been rebranded as EventBridge, so create a new documentation category

Relates #9330

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
NONE
```

Output from acceptance testing:

N/A

2020-10-29 19:42 UTC, bflad requested changes

2020-10-29 19:42 UTC, bflad commented on website/allowed-subcategories.txt
> +EventBridge (fka CloudWatch Events)
I'm not sure if `fka` (formerly known as) is a globally known acronym, especially for non-native English speakers. I would recommend just dropping it.

2020-10-29 20:09 UTC, bflad approved these changes
Onward and upward! 🚀

2020-10-29 21:06 UTC, merged

2020-11-02 15:24 UTC, paulca99 commented
Just read "on the default EventBus" .... what if you're using a different EventBus ?