[WIP] New resource aws_autoscalingplans_scaling_plan
terraform-providers/terraform-provider-aws pull request #8965
Opened 2019-06-12 17:35 UTC by ewbankkit

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Fixes #6562

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
FEATURES:

* New Resource: aws_autoscalingplans_scaling_plan (#6562)
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

2019-06-12 17:35 UTC, ewbankkit commented
Currently includes the commit from https://github.com/terraform-providers/terraform-provider-aws/pull/8962.

2019-06-12 17:40 UTC, ewbankkit commented
The name **aws_autoscalingplans_scaling_plan** is just a straw man as the resource is implemented via a new `autoscalingplans` AWS API and CloudFormation names its [equivalent resource](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-autoscalingplans-scalingplan.html) similarly.
All the AWS documentation and AWS console just calls them **Auto Scaling scaling plans* so `aws_autoscaling_scaling_plan` may be the better name and also consolidate the documentation into the _Autoscaling_ section rather than a separate section.

2019-06-18 18:02 UTC, ewbankkit commented
Removing _WIP_.
I've actually come to be OK with the name `aws_autoscalingplans_scaling_plan`.

2019-07-26 18:49 UTC, ewbankkit commented
Rebased to fix merge conflict.

2019-10-02 14:38 UTC, ewbankkit commented
Rebased to fix merge conflict.
Acceptance tests:
```console
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAwsAutoScalingPlansScalingPlan_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws/ -v -count 1 -parallel 20 -run=TestAccAwsAutoScalingPlansScalingPlan_ -timeout 120m
=== RUN   TestAccAwsAutoScalingPlansScalingPlan_basicDynamicScaling
=== PAUSE TestAccAwsAutoScalingPlansScalingPlan_basicDynamicScaling
=== RUN   TestAccAwsAutoScalingPlansScalingPlan_basicPredictiveScaling
=== PAUSE TestAccAwsAutoScalingPlansScalingPlan_basicPredictiveScaling
=== RUN   TestAccAwsAutoScalingPlansScalingPlan_basicUpdate
=== PAUSE TestAccAwsAutoScalingPlansScalingPlan_basicUpdate
=== CONT  TestAccAwsAutoScalingPlansScalingPlan_basicDynamicScaling
=== CONT  TestAccAwsAutoScalingPlansScalingPlan_basicUpdate
=== CONT  TestAccAwsAutoScalingPlansScalingPlan_basicPredictiveScaling
--- PASS: TestAccAwsAutoScalingPlansScalingPlan_basicPredictiveScaling (80.60s)
--- PASS: TestAccAwsAutoScalingPlansScalingPlan_basicDynamicScaling (81.03s)
--- PASS: TestAccAwsAutoScalingPlansScalingPlan_basicUpdate (112.85s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	112.920s
``

2019-10-05 21:09 UTC, ewbankkit commented
Rebased and did the Terraform Plugin SDK migration for the new resource.
Re-ran acceptance tests:

```console
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAwsAutoScalingPlansScalingPlan_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws/ -v -count 1 -parallel 20 -run=TestAccAwsAutoScalingPlansScalingPlan_ -timeout 120m
go: finding github.com/terraform-providers/terraform-provider-tls v2.1.1+incompatible
go: finding github.com/terraform-providers/terraform-provider-tls v2.1.1+incompatible
=== RUN   TestAccAwsAutoScalingPlansScalingPlan_basicDynamicScaling
=== PAUSE TestAccAwsAutoScalingPlansScalingPlan_basicDynamicScaling
=== RUN   TestAccAwsAutoScalingPlansScalingPlan_basicPredictiveScaling
=== PAUSE TestAccAwsAutoScalingPlansScalingPlan_basicPredictiveScaling
=== RUN   TestAccAwsAutoScalingPlansScalingPlan_basicUpdate
=== PAUSE TestAccAwsAutoScalingPlansScalingPlan_basicUpdate
=== CONT  TestAccAwsAutoScalingPlansScalingPlan_basicDynamicScaling
=== CONT  TestAccAwsAutoScalingPlansScalingPlan_basicUpdate
=== CONT  TestAccAwsAutoScalingPlansScalingPlan_basicPredictiveScaling
--- PASS: TestAccAwsAutoScalingPlansScalingPlan_basicDynamicScaling (76.66s)
--- PASS: TestAccAwsAutoScalingPlansScalingPlan_basicPredictiveScaling (77.07s)
--- PASS: TestAccAwsAutoScalingPlansScalingPlan_basicUpdate (104.08s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	104.122s
```

2019-10-25 22:41 UTC, ewbankkit commented on aws/validators.go
> +// validateStringDoesNotContainAny returns a SchemaValidateFunc which validates that the
Track https://github.com/hashicorp/terraform-plugin-sdk/pull/212.

2019-11-07 14:21 UTC, ewbankkit commented
### TODO

* Any documentation changes for https://github.com/terraform-providers/terraform-provider-aws/pull/10684
* Track https://github.com/terraform-providers/terraform-provider-aws/pull/10768 to use `StringDoesNotContainAny`

2019-11-07 15:18 UTC, jcruzfrontline commented
@bflad - This would be great to get this merged. We would like to utilize this feature in our staging & production environment without manual steps. Thank you for your hard work on this @ewbankkit !

2019-11-14 21:55 UTC, mr-ransel commented
I heartily second @jcruzfrontline . We are getting ready to fork and rebuild terraform internally to make use of this change ourselves, just because of the inherent danger in having to manage predictive scaling plans by hand.

2020-02-11 10:09 UTC, darmawanaris commented
Hi @ewbankkit , why this PR is not merged yet ?

2020-05-07 11:58 UTC, ewbankkit commented
Revisit, considering https://github.com/terraform-providers/terraform-provider-aws/pull/13194.

2020-05-11 11:14 UTC, ewbankkit commented on aws/resource_aws_autoscalingplans_scaling_plan.go
> +func stableMapHash(m map[string]interface{}) int {
Verify whether this is needed after merge of https://github.com/terraform-providers/terraform-provider-aws/pull/12740, pulling in https://github.com/hashicorp/terraform-plugin-sdk/pull/362.

2020-05-21 20:52 UTC, ewbankkit commented on aws/resource_aws_autoscalingplans_scaling_plan.go
> +func stableMapHash(m map[string]interface{}) int {
Removed custom set hash functions.

2020-05-21 20:52 UTC, ewbankkit commented
Re-ran acceptance tests:

```console
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAwsAutoScalingPlansScalingPlan_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws/ -v -count 1 -parallel 20 -run=TestAccAwsAutoScalingPlansScalingPlan_ -timeout 120m
=== RUN   TestAccAwsAutoScalingPlansScalingPlan_basicDynamicScaling
=== PAUSE TestAccAwsAutoScalingPlansScalingPlan_basicDynamicScaling
=== RUN   TestAccAwsAutoScalingPlansScalingPlan_basicPredictiveScaling
=== PAUSE TestAccAwsAutoScalingPlansScalingPlan_basicPredictiveScaling
=== RUN   TestAccAwsAutoScalingPlansScalingPlan_basicUpdate
=== PAUSE TestAccAwsAutoScalingPlansScalingPlan_basicUpdate
=== RUN   TestAccAwsAutoScalingPlansScalingPlan_disappears
=== PAUSE TestAccAwsAutoScalingPlansScalingPlan_disappears
=== CONT  TestAccAwsAutoScalingPlansScalingPlan_basicDynamicScaling
=== CONT  TestAccAwsAutoScalingPlansScalingPlan_disappears
=== CONT  TestAccAwsAutoScalingPlansScalingPlan_basicUpdate
=== CONT  TestAccAwsAutoScalingPlansScalingPlan_basicPredictiveScaling
--- PASS: TestAccAwsAutoScalingPlansScalingPlan_disappears (53.23s)
--- PASS: TestAccAwsAutoScalingPlansScalingPlan_basicDynamicScaling (57.27s)
--- PASS: TestAccAwsAutoScalingPlansScalingPlan_basicUpdate (80.78s)
--- PASS: TestAccAwsAutoScalingPlansScalingPlan_basicPredictiveScaling (81.58s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	81.641s
```

2020-07-06 19:54 UTC, ewbankkit commented
Rebase to fix merge conflicts and simplify acceptance tests:

```console
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAwsAutoScalingPlansScalingPlan_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws/ -v -count 1 -parallel 20 -run=TestAccAwsAutoScalingPlansScalingPlan_ -timeout 120m
=== RUN   TestAccAwsAutoScalingPlansScalingPlan_basicDynamicScaling
=== PAUSE TestAccAwsAutoScalingPlansScalingPlan_basicDynamicScaling
=== RUN   TestAccAwsAutoScalingPlansScalingPlan_basicPredictiveScaling
=== PAUSE TestAccAwsAutoScalingPlansScalingPlan_basicPredictiveScaling
=== RUN   TestAccAwsAutoScalingPlansScalingPlan_basicUpdate
=== PAUSE TestAccAwsAutoScalingPlansScalingPlan_basicUpdate
=== RUN   TestAccAwsAutoScalingPlansScalingPlan_disappears
=== PAUSE TestAccAwsAutoScalingPlansScalingPlan_disappears
=== CONT  TestAccAwsAutoScalingPlansScalingPlan_basicDynamicScaling
=== CONT  TestAccAwsAutoScalingPlansScalingPlan_disappears
=== CONT  TestAccAwsAutoScalingPlansScalingPlan_basicUpdate
=== CONT  TestAccAwsAutoScalingPlansScalingPlan_basicPredictiveScaling
--- PASS: TestAccAwsAutoScalingPlansScalingPlan_disappears (52.61s)
--- PASS: TestAccAwsAutoScalingPlansScalingPlan_basicUpdate (79.53s)
--- PASS: TestAccAwsAutoScalingPlansScalingPlan_basicPredictiveScaling (81.24s)
--- PASS: TestAccAwsAutoScalingPlansScalingPlan_basicDynamicScaling (86.21s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	86.280s
```

2020-08-05 02:43 UTC, maitdaddy commented
@ewbankkit We salute you for all your efforts on this request!

2020-08-05 03:35 UTC, jcruzfrontline commented
@ewbankkit  - I second that!

2020-08-05 12:28 UTC, ewbankkit commented
This is on [this quarter's road map](https://github.com/terraform-providers/terraform-provider-aws/blob/3713ea9f8ce8f3bb1fd572beed8b1fa1967af7ff/ROADMAP.md#issues-and-enhancements).

2020-08-13 16:46 UTC, kyprifog commented
Excited to see this one make it in

2020-08-16 21:35 UTC, ewbankkit commented
Rebased and upgraded new code to Plugin SDK v2.
Re-ran acceptance tests:

```console
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAwsAutoScalingPlansScalingPlan_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAwsAutoScalingPlansScalingPlan_ -timeout 120m
=== RUN   TestAccAwsAutoScalingPlansScalingPlan_basicDynamicScaling
=== PAUSE TestAccAwsAutoScalingPlansScalingPlan_basicDynamicScaling
=== RUN   TestAccAwsAutoScalingPlansScalingPlan_basicPredictiveScaling
=== PAUSE TestAccAwsAutoScalingPlansScalingPlan_basicPredictiveScaling
=== RUN   TestAccAwsAutoScalingPlansScalingPlan_basicUpdate
=== PAUSE TestAccAwsAutoScalingPlansScalingPlan_basicUpdate
=== RUN   TestAccAwsAutoScalingPlansScalingPlan_disappears
=== PAUSE TestAccAwsAutoScalingPlansScalingPlan_disappears
=== CONT  TestAccAwsAutoScalingPlansScalingPlan_basicDynamicScaling
=== CONT  TestAccAwsAutoScalingPlansScalingPlan_disappears
=== CONT  TestAccAwsAutoScalingPlansScalingPlan_basicUpdate
=== CONT  TestAccAwsAutoScalingPlansScalingPlan_basicPredictiveScaling
=== CONT  TestAccAwsAutoScalingPlansScalingPlan_disappears
    resource_aws_autoscalingplans_scaling_plan_test.go:268: [INFO] Got non-empty plan, as expected
--- PASS: TestAccAwsAutoScalingPlansScalingPlan_basicDynamicScaling (52.75s)
--- PASS: TestAccAwsAutoScalingPlansScalingPlan_basicPredictiveScaling (61.57s)
--- PASS: TestAccAwsAutoScalingPlansScalingPlan_disappears (61.58s)
--- PASS: TestAccAwsAutoScalingPlansScalingPlan_basicUpdate (83.10s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	83.157s
```

2020-10-07 17:24 UTC, ssabo commented
I am not sure who to direct this question to. What is preventing this patch from being merged currently?

2020-10-16 15:36 UTC, anGie44 requested changes
Thank you for this PR @ewbankkit! Design looks great overall. It seems though the waiter methods may need some tweaking in the `Pending` states values as the following tests are consistently failing in Commercial and Gov Cloud:

```
--- FAIL: TestAccAwsAutoScalingPlansScalingPlan_basicDynamicScaling (9.54s)
--- FAIL: TestAccAwsAutoScalingPlansScalingPlan_disappears (9.62s)
--- FAIL: TestAccAwsAutoScalingPlansScalingPlan_basicUpdate (9.66s)
--- FAIL: TestAccAwsAutoScalingPlansScalingPlan_basicPredictiveScaling (36.08s)
```

with the error(s):
```
Error: error waiting for Auto Scaling Scaling Plan (tf-acc-test-6121015609472249022/1) to be created: unexpected state 'NotFound', wanted target 'Active, ActiveWithProblems'. last error: %!s(<nil>)
```
```
Error: error waiting for Auto Scaling Scaling Plan (tf-acc-test-6406453948128485035/1) to be deleted: unexpected state 'Active', wanted target 'NotFound'. last error: %!s(<nil>)
```

2020-10-16 19:02 UTC, ewbankkit commented
Modified the status codes used by the create and delete waiters to better handle eventual consistency.

```console
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAwsAutoScalingPlansScalingPlan_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAwsAutoScalingPlansScalingPlan_ -timeout 120m
=== RUN   TestAccAwsAutoScalingPlansScalingPlan_basicDynamicScaling
=== PAUSE TestAccAwsAutoScalingPlansScalingPlan_basicDynamicScaling
=== RUN   TestAccAwsAutoScalingPlansScalingPlan_basicPredictiveScaling
=== PAUSE TestAccAwsAutoScalingPlansScalingPlan_basicPredictiveScaling
=== RUN   TestAccAwsAutoScalingPlansScalingPlan_basicUpdate
=== PAUSE TestAccAwsAutoScalingPlansScalingPlan_basicUpdate
=== RUN   TestAccAwsAutoScalingPlansScalingPlan_disappears
=== PAUSE TestAccAwsAutoScalingPlansScalingPlan_disappears
=== CONT  TestAccAwsAutoScalingPlansScalingPlan_basicDynamicScaling
=== CONT  TestAccAwsAutoScalingPlansScalingPlan_basicUpdate
=== CONT  TestAccAwsAutoScalingPlansScalingPlan_disappears
=== CONT  TestAccAwsAutoScalingPlansScalingPlan_basicPredictiveScaling
=== CONT  TestAccAwsAutoScalingPlansScalingPlan_disappears
    resource_aws_autoscalingplans_scaling_plan_test.go:257: [INFO] Got non-empty plan, as expected
--- PASS: TestAccAwsAutoScalingPlansScalingPlan_disappears (57.76s)
--- PASS: TestAccAwsAutoScalingPlansScalingPlan_basicDynamicScaling (60.68s)
--- PASS: TestAccAwsAutoScalingPlansScalingPlan_basicPredictiveScaling (61.08s)
--- PASS: TestAccAwsAutoScalingPlansScalingPlan_basicUpdate (93.65s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	93.687s
```

2020-10-19 15:43 UTC, anGie44 commented on website/docs/r/autoscalingplans_scaling_plan.html.markdown
> +An [`aws_iam_service_linked_role`](/docs/providers/aws/r/iam_service_linked_role.html) resource can be used to manually managed this role.
small correction:  
```suggestion
An [`aws_iam_service_linked_role`](/docs/providers/aws/r/iam_service_linked_role.html) resource can be used to manually manage this role.
```

2020-10-19 16:58 UTC, ewbankkit commented
Added `testAccPreCheckIamServiceLinkedRole` and used if for those acceptance tests that use predictive scaling.
Without the service-linked role:

```console
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAwsAutoScalingPlansScalingPlan_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAwsAutoScalingPlansScalingPlan_ -timeout 120m
=== RUN   TestAccAwsAutoScalingPlansScalingPlan_basicDynamicScaling
=== PAUSE TestAccAwsAutoScalingPlansScalingPlan_basicDynamicScaling
=== RUN   TestAccAwsAutoScalingPlansScalingPlan_basicPredictiveScaling
=== PAUSE TestAccAwsAutoScalingPlansScalingPlan_basicPredictiveScaling
=== RUN   TestAccAwsAutoScalingPlansScalingPlan_basicUpdate
=== PAUSE TestAccAwsAutoScalingPlansScalingPlan_basicUpdate
=== RUN   TestAccAwsAutoScalingPlansScalingPlan_disappears
=== PAUSE TestAccAwsAutoScalingPlansScalingPlan_disappears
=== CONT  TestAccAwsAutoScalingPlansScalingPlan_basicDynamicScaling
=== CONT  TestAccAwsAutoScalingPlansScalingPlan_disappears
=== CONT  TestAccAwsAutoScalingPlansScalingPlan_basicUpdate
=== CONT  TestAccAwsAutoScalingPlansScalingPlan_basicPredictiveScaling
=== CONT  TestAccAwsAutoScalingPlansScalingPlan_basicUpdate
    provider_test.go:601: skipping tests; missing IAM service-linked role /aws-service-role/autoscaling-plans. Please create the role and retry
--- SKIP: TestAccAwsAutoScalingPlansScalingPlan_basicUpdate (0.87s)
=== CONT  TestAccAwsAutoScalingPlansScalingPlan_basicPredictiveScaling
    provider_test.go:601: skipping tests; missing IAM service-linked role /aws-service-role/autoscaling-plans. Please create the role and retry
--- SKIP: TestAccAwsAutoScalingPlansScalingPlan_basicPredictiveScaling (0.98s)
=== CONT  TestAccAwsAutoScalingPlansScalingPlan_disappears
    resource_aws_autoscalingplans_scaling_plan_test.go:263: [INFO] Got non-empty plan, as expected
--- PASS: TestAccAwsAutoScalingPlansScalingPlan_disappears (35.14s)
--- PASS: TestAccAwsAutoScalingPlansScalingPlan_basicDynamicScaling (59.48s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	59.523s
```

after [manually creating the service-linked role](https://docs.aws.amazon.com/autoscaling/plans/userguide/aws-auto-scaling-service-linked-roles.html#create-service-linked-role-manual):

```console
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAwsAutoScalingPlansScalingPlan_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAwsAutoScalingPlansScalingPlan_ -timeout 120m
=== RUN   TestAccAwsAutoScalingPlansScalingPlan_basicDynamicScaling
=== PAUSE TestAccAwsAutoScalingPlansScalingPlan_basicDynamicScaling
=== RUN   TestAccAwsAutoScalingPlansScalingPlan_basicPredictiveScaling
=== PAUSE TestAccAwsAutoScalingPlansScalingPlan_basicPredictiveScaling
=== RUN   TestAccAwsAutoScalingPlansScalingPlan_basicUpdate
=== PAUSE TestAccAwsAutoScalingPlansScalingPlan_basicUpdate
=== RUN   TestAccAwsAutoScalingPlansScalingPlan_disappears
=== PAUSE TestAccAwsAutoScalingPlansScalingPlan_disappears
=== CONT  TestAccAwsAutoScalingPlansScalingPlan_basicDynamicScaling
=== CONT  TestAccAwsAutoScalingPlansScalingPlan_disappears
=== CONT  TestAccAwsAutoScalingPlansScalingPlan_basicUpdate
=== CONT  TestAccAwsAutoScalingPlansScalingPlan_basicPredictiveScaling
=== CONT  TestAccAwsAutoScalingPlansScalingPlan_disappears
    resource_aws_autoscalingplans_scaling_plan_test.go:263: [INFO] Got non-empty plan, as expected
--- PASS: TestAccAwsAutoScalingPlansScalingPlan_disappears (42.35s)
--- PASS: TestAccAwsAutoScalingPlansScalingPlan_basicPredictiveScaling (56.60s)
--- PASS: TestAccAwsAutoScalingPlansScalingPlan_basicDynamicScaling (64.38s)
--- PASS: TestAccAwsAutoScalingPlansScalingPlan_basicUpdate (78.71s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	78.746s
```

2020-10-21 05:47 UTC, anGie44 commented on aws/internal/service/autoscalingplans/finder/finder.go
> +// Returns returns nil and potentially an API error if no scaling plan is found.
Nit: 
```suggestion
// Returns nil and potentially an API error if no scaling plan is found.
```

2020-10-21 15:20 UTC, anGie44 approved these changes
Looks great and acceptance tests have been corrected 👍 

Output of acceptance tests (Commercial):
```
--- PASS: TestProvider_impl (0.12s)
--- PASS: TestProvider (1.81s)
--- PASS: TestAccAWSProvider_Region_AwsGovCloudUs (36.00s)
--- PASS: TestAccAWSProvider_Region_AwsCommercial (36.88s)
--- PASS: TestAccAWSProvider_Region_AwsChina (37.02s)
--- PASS: TestAccAWSProvider_IgnoreTags_KeyPrefixes_None (46.29s)
--- PASS: TestAccAWSProvider_Endpoints (46.14s)
--- PASS: TestAccAWSProvider_IgnoreTags_Keys_One (46.60s)
--- PASS: TestAccAWSProvider_IgnoreTags_EmptyConfigurationBlock (46.34s)
--- PASS: TestAccAWSProvider_IgnoreTags_KeyPrefixes_One (46.83s)
--- PASS: TestAccAWSProvider_IgnoreTags_Keys_None (46.92s)
--- PASS: TestAccAWSProvider_IgnoreTags_KeyPrefixes_Multiple (47.03s)
--- PASS: TestAccAWSProvider_IgnoreTags_Keys_Multiple (47.26s)
--- PASS: TestAccAWSProvider_AssumeRole_Empty (48.30s)
--- PASS: TestAccAwsAutoScalingPlansScalingPlan_disappears (73.48s)
--- PASS: TestAccAwsAutoScalingPlansScalingPlan_basicDynamicScaling (92.06s)
--- PASS: TestAccAwsAutoScalingPlansScalingPlan_basicPredictiveScaling (92.39s)
--- PASS: TestAccAwsAutoScalingPlansScalingPlan_basicUpdate (117.60s)
```
Output of acceptance tests (Gov Cloud):
```
--- PASS: TestProvider_impl (0.17s)
--- PASS: TestProvider (1.17s)
--- SKIP: TestAccAwsAutoScalingPlansScalingPlan_basicPredictiveScaling (0.88s)
--- SKIP: TestAccAwsAutoScalingPlansScalingPlan_basicUpdate (0.56s)
--- PASS: TestAccAWSProvider_Region_AwsChina (34.51s)
--- PASS: TestAccAWSProvider_Region_AwsGovCloudUs (34.30s)
--- PASS: TestAccAWSProvider_Region_AwsCommercial (35.68s)
--- PASS: TestAccAWSProvider_Endpoints (43.40s)
--- PASS: TestAccAWSProvider_IgnoreTags_Keys_Multiple (42.95s)
--- PASS: TestAccAWSProvider_IgnoreTags_Keys_None (43.51s)
--- PASS: TestAccAWSProvider_IgnoreTags_Keys_One (43.36s)
--- PASS: TestAccAWSProvider_IgnoreTags_KeyPrefixes_One (44.37s)
--- PASS: TestAccAWSProvider_AssumeRole_Empty (44.08s)
--- PASS: TestAccAWSProvider_IgnoreTags_KeyPrefixes_None (44.39s)
--- PASS: TestAccAWSProvider_IgnoreTags_KeyPrefixes_Multiple (44.28s)
--- PASS: TestAccAWSProvider_IgnoreTags_EmptyConfigurationBlock (44.40s)
--- PASS: TestAccAwsAutoScalingPlansScalingPlan_basicDynamicScaling (67.52s)
--- PASS: TestAccAwsAutoScalingPlansScalingPlan_disappears (71.39s)
```

2020-10-21 15:20 UTC, merged